name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - website_dev  # or your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or your desired Node version

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Build the Next.js app
      - name: Build Next.js App
        run: npm run build


      # 6. Deploy the exported site from the "out" directory to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: website_dev